### ISSUE TITLE
[Bug Report]

### ISSUE THREAD

**Issue by Motophan** [vonhoro/Automate-encoding#13]
Error: ENOENT: no such file or directory, scandir 'D:\Encode machien\x64-TestAll\jobCrop preview\Take number - 1\screenshots'
    at Object.readdirSync (fs.js:1021:3)
    at jimpAnalysis (D:\Encode machien\x64-TestAll\Modules\jimpAnalysis.js:16:27)
    at main (D:\Encode machien\x64-TestAll\doEverything.js:280:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -4058,
  syscall: 'scandir',
  code: 'ENOENT',
  path: 'D:\\Encode machien\\x64-TestAll\\jobCrop preview\\Take number - 1\\screenshots'
![image](https://user-images.githubusercontent.com/42502676/100048717-f35f9e00-2dc1-11eb-9cd8-e3c8098b36c5.png)

**Comment by Motophan** [comment]
SOme things point at \\jobCrop\\Take number - 1\\screenshots preview, others point at \\Crop preview\\Take number - 1\\screenshots

**Comment by vonhoro** [comment]
Fixed
